// Systematic uncertainties

NUTIME = 3.5
NUBARTIME = 3.5
LAMASS = 40

ERR_NUE_SIG = 0.02
ERR_NUE_SIGBAR = 0.02
ERR_NUMU_SIG = 0.05
ERR_NUMU_SIGBAR = 0.05

ERR_NUMU_BG = 0.05
ERR_NUE_BG = 0.05
ERR_NUTAU_BG = 0.2
ERR_NUE_BGBAR = 0.05
ERR_NC_BGDIS = 0.1

// tau channels (hadronic decays only)
BR_HADR = 0.65
BR_LEPT_E = 0.17
HADR_EFF = 0.30             // signal eff from 2008.12769 (see discussion on page 43)
NC_EFF_NUTAU_HADR = 0.005   // from Aurisano's talk, NC bg rejection eff 
