#! /bin/sh
# replace the string GLB_LINKER_FLAGS with the correct values
# infered from source/libglobes.la

cd $PWD

# Fixing library depencies
l=`less source/libglb.la|grep dependency_libs`
l2=${l#dependency_libs=\'}
depenlib="${l2%\'} -lstdc++" 

sed 's/GLB_LINKER_FLAGS/${depenlib}/g' $1 > $2

chmod u+x $2