#line 69 "glb_lexer.l"
#if HAVE_CONFIG_H   /* config.h should come before any other includes */
#  include "config.h"
#endif



#line 9 "glb_lexer.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap(n) 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 72
#define YY_END_OF_BUFFER 73
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[432] =
    {   0,
       68,   68,   19,   19,   68,   68,   68,   68,   68,   68,
       68,   68,   68,   68,   68,   68,   68,   68,   68,   68,
       68,   68,   68,   68,   68,   68,   68,   68,   68,   68,
       68,   68,   68,   68,    5,    5,    2,    2,   39,   39,
       73,   70,   68,   71,   37,   70,   70,   70,   70,   70,
       59,   47,   48,   66,   25,   26,   66,   27,   66,   25,
       66,   66,   66,   66,   66,   20,   19,   72,   21,   57,
       48,   23,   24,   48,   48,   48,   48,   48,   48,   70,
       70,   70,   70,   70,   70,   70,    5,    7,    6,    2,
        3,   39,   38,   68,   56,   56,   56,   60,   60,   60,

        0,   67,   62,    4,    1,   61,   59,    0,   66,   25,
       26,   66,   27,   66,   66,   25,   66,   66,   66,   66,
       66,   20,   19,   58,   58,   58,   58,   58,   58,   58,
       58,   49,   49,   49,   50,   50,   50,   51,   51,   51,
       52,   52,   52,   53,   53,   53,   54,   54,   54,   55,
       55,   55,    5,    6,    6,    8,    2,   39,   56,   56,
       56,   60,   60,   60,    0,   67,    0,   61,    0,    0,
       65,   66,   66,   66,   25,   66,   66,   66,   66,   17,
       58,   58,   58,   58,   58,   58,   58,   58,   58,   49,
       49,   49,   50,   50,   50,   51,   51,   51,   52,   52,

       52,   53,   53,   53,   54,   54,   54,   55,   55,   55,
       56,   56,   60,   60,    0,    0,   64,    0,   63,   66,
       66,   66,   25,   15,   66,   66,   11,   58,   58,   58,
       58,   58,   58,   58,   58,   49,   49,   50,   50,   51,
       51,   52,   52,   53,   53,   54,   54,   55,   55,   56,
       56,   60,   60,    0,   66,   66,   14,   66,   66,   66,
       58,   58,   58,   58,   58,   58,   58,   58,   49,   49,
       50,   50,   51,   51,   52,   52,   53,   53,   54,   54,
       55,   55,   56,    9,   60,   60,    0,   28,   29,   30,
       66,   13,   66,   16,   58,   58,   58,   58,   58,   58,

       58,   58,   49,   50,   51,   52,   53,   54,   55,   56,
       60,   60,    0,   28,   29,   30,   12,   18,   58,   32,
       58,   58,   58,   31,   58,   58,   58,   49,   50,   51,
       52,   53,   54,   55,   56,   60,   40,   69,   58,   58,
       58,   22,   58,   58,   58,   49,   50,   51,   52,   53,
       54,   55,   56,   41,   58,   58,   58,   58,   58,   58,
       58,   49,   50,   51,   52,   53,   54,   55,   10,   58,
       58,   58,   58,   58,   58,   43,   45,   33,   58,   58,
       58,   58,   42,   58,   58,   58,   58,   58,   58,   44,
       46,   58,   58,   58,   58,   58,   58,   58,   58,   58,

       58,   58,   58,   58,   58,   34,   58,   35,   58,   58,
       58,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       58,   58,   58,   58,   58,   58,   58,   36,   58,   58,
        0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    7,    8,    1,    1,    1,
        1,    9,   10,    1,   11,   12,   13,   14,   14,   14,
       14,   14,   14,   14,   14,   14,   14,   15,    1,   16,
        1,   17,    1,   18,   19,   20,   21,   22,   23,   24,
       25,   24,   24,   24,   24,   26,   27,   28,   29,   24,
       24,   30,   31,   32,   33,   24,   24,   34,   24,   24,
        1,    1,    1,    1,   35,    1,   36,   37,   38,   39,

       40,   41,   42,   43,   44,   24,   45,   46,   47,   48,
       49,   24,   24,   50,   51,   52,   53,   54,   24,   55,
       56,   24,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[57] =
    {   0,
        1,    2,    3,    4,    5,    1,    1,    1,    6,    1,
        1,    1,    1,    7,    1,    1,    1,    1,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    7,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8
    } ;

static yyconst flex_int16_t yy_base[464] =
    {   0,
        0,    0,   55,   57,   23,   27,   63,   99,  141,  183,
      219,  255,  291,  327,  363,  399,  435,  471,  507,  543,
       80,   84,  123,  127,  147,  164,  178,  200,  204,  237,
      241,  274,  310,  346,   63,   67,  824,  823,  820,  819,
      823,  828,  820,  828,  828,   60,   31,  817,  806,   74,
       79,  828,  828,    0,  574,  377,  790,   73,   46,  770,
      771,  768,  762,  761,  757,    0,  810,  828,  828,  828,
       47,  828,  828,  773,  770,  771,  767,  766,    0,   72,
       77,  114,  116,  126,  134,  138,    0,  828,   99,    0,
      828,    0,  828,  804,    0,  782,  781,    0,  759,  762,

      776,    0,  132,  828,  828,  199,  287,  197,    0,    0,
      379,  769,  150,  763,  749,  757,  743,  757,  753,  747,
      741,    0,  789,    0,  754,   51,  746,  740,  737,  740,
      739,    0,  761,  760,    0,  759,  758,    0,  757,  756,
        0,  755,  754,    0,  753,  752,    0,  751,  750,    0,
      749,  748,    0,  114,  132,  828,    0,    0,    0,  738,
      735,    0,  716,  717,  740,    0,  251,  260,  307,  751,
      750,  742,  714,  710,  710,  679,  678,  670,  671,    0,
        0,  670,  658,  648,  658,  653,  643,  604,  600,    0,
      619,  616,    0,  617,  614,    0,  615,  611,    0,  611,

      608,    0,  609,  606,    0,  607,  603,    0,  601,  597,
      607,  596,  589,  570,  570,  604,  603,  602,  601,  578,
      563,  559,  567,    0,  555,  554,    0,  560,  553,  564,
      550,  546,  541,  535,  534,  565,  555,  563,  553,  559,
      548,  556,  546,  554,  544,  552,  542,  550,  540,  550,
      564,  517,  524,  547,  432,  526,    0,  509,  525,  508,
      520,  520,  505,  505,  510,  500,  515,  514,  525,  538,
      522,  536,  520,  534,  518,  532,  516,  530,  514,  528,
      512,  526,  499,  828,  486,  480,  505,  606,  413,  213,
      481,    0,  486,    0,  470,  472,  179,  477,  460,  480,

      473,  472,  478,  476,  475,  474,  473,  472,  471,  472,
      451,  451,  465,    0,  449,  300,    0,    0,  446,    0,
      453,  458,  446,    0,  450,  446,  437,  451,  445,  442,
      441,  440,  439,  438,  435,  415,    0,  828,  407,  423,
      149,    0,  413,  410,  408,  418,  415,  414,  413,  408,
      406,  405,  428,    0,  385,  217,  378,  376,  378,  383,
      382,  415,  414,  413,  412,  403,  396,  394,  828,  360,
      345,  342,  345,  346,  351,  355,  354,    0,  340,  339,
      345,  330,    0,  329,  327,  335,  320,  319,  326,    0,
        0,  317,  322,  320,  323,  318,  319,  308,  301,  306,

      299,  301,  312,  298,  305,    0,  298,    0,  297,  285,
      284,  280,  278,  277,  274,  270,  263,  260,  253,  267,
      262,  239,  247,  252,  242,  226,  219,    0,  214,  211,
      828,  658,  666,  674,  682,  222,  217,  687,  689,  697,
      209,  201,  172,  168,  135,  102,   89,   54,  705,  713,
      721,  729,  731,  733,  735,  737,  739,  741,  743,  745,
      747,  749,  751
    } ;

static yyconst flex_int16_t yy_def[464] =
    {   0,
      431,    1,  432,  432,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,  433,  433,  434,  434,  435,  435,
      431,  431,  431,  431,  431,  436,  437,  438,  431,  431,
      431,  431,  431,  439,  439,  439,  439,  439,  439,   55,
      439,  439,  439,  439,  439,  440,  431,  431,  431,  431,
      441,  431,  431,  441,  441,  441,  441,  441,  441,  442,
      443,  444,  445,  446,  447,  448,  449,  431,  450,  451,
      431,  452,  431,  431,  453,  453,  453,  454,  454,  454,

      431,  455,  431,  431,  431,  431,  431,  431,  439,   55,
      439,  439,  439,  439,  439,   55,  439,  439,  439,  439,
      439,  440,  431,  456,  456,  456,  456,  456,  456,  456,
      456,  457,  457,  457,  458,  458,  458,  459,  459,  459,
      460,  460,  460,  461,  461,  461,  462,  462,  462,  463,
      463,  463,  449,  450,  450,  431,  451,  452,  453,  453,
      453,  454,  454,  454,  431,  455,  431,  431,  431,  431,
      431,  439,  439,  439,   55,  439,  439,  439,  439,  439,
      456,  456,  456,  456,  456,  456,  456,  456,  456,  457,
      457,  457,  458,  458,  458,  459,  459,  459,  460,  460,

      460,  461,  461,  461,  462,  462,  462,  463,  463,  463,
      453,  453,  454,  454,  431,  431,  431,  431,  431,  439,
      439,  439,   55,  439,  439,  439,  439,  456,  456,  456,
      456,  456,  456,  456,  456,  457,  457,  458,  458,  459,
      459,  460,  460,  461,  461,  462,  462,  463,  463,  453,
      453,  454,  454,  431,  439,  439,  439,  439,  439,  439,
      456,  456,  456,  456,  456,  456,  456,  456,  457,  457,
      458,  458,  459,  459,  460,  460,  461,  461,  462,  462,
      463,  463,  453,  431,  454,  454,  431,  439,  439,  439,
      439,  439,  439,  439,  456,  456,  456,  456,  456,  456,

      456,  456,  457,  458,  459,  460,  461,  462,  463,  453,
      454,  454,  431,  288,  439,  439,  439,  439,  456,  456,
      456,  456,  456,  456,  456,  456,  456,  457,  458,  459,
      460,  461,  462,  463,  453,  454,  454,  431,  456,  456,
      456,  456,  456,  456,  456,  457,  458,  459,  460,  461,
      462,  463,  453,  454,  456,  456,  456,  456,  456,  456,
      456,  457,  458,  459,  460,  461,  462,  463,  431,  456,
      456,  456,  456,  456,  456,  456,  456,  456,  456,  456,
      456,  456,  456,  456,  456,  456,  456,  456,  456,  456,
      456,  456,  456,  456,  456,  456,  456,  456,  456,  456,

      456,  456,  456,  456,  456,  456,  456,  456,  456,  456,
      456,  456,  456,  456,  456,  456,  456,  456,  456,  456,
      456,  456,  456,  456,  456,  456,  456,  456,  456,  456,
        0,  431,  431,  431,  431,  431,  431,  431,  431,  431,
      431,  431,  431,  431,  431,  431,  431,  431,  431,  431,
      431,  431,  431,  431,  431,  431,  431,  431,  431,  431,
      431,  431,  431
    } ;

static yyconst flex_int16_t yy_nxt[885] =
    {   0,
       42,   43,   44,   42,   45,   46,   47,   48,   42,   42,
       42,   49,   50,   51,   52,   42,   42,   53,   54,   54,
       54,   54,   55,   54,   54,   54,   56,   57,   54,   54,
       54,   58,   54,   54,   42,   54,   54,   59,   54,   60,
       61,   54,   54,   62,   54,   54,   56,   63,   54,   64,
       65,   58,   54,   54,   54,   54,   67,   68,   67,   68,
       54,  150,   55,   54,   54,   88,   55,   54,   99,   88,
       54,   89,   54,   54,   54,   89,   54,   54,   69,   70,
       71,   96,  104,  125,  100,   80,  105,   97,  114,   80,
      106,  113,  107,  133,  183,  115,  147,  126,  136,  134,

       54,  108,   55,   54,  137,  113,  184,  155,  113,  144,
       54,  156,   54,   54,   69,   70,   71,   54,  108,   55,
       54,   54,  431,   55,   54,  113,  431,   54,   81,   54,
       54,   54,   81,   54,   54,  139,   54,  142,   55,   54,
      155,  140,  141,  143,  156,  103,   54,  145,   54,   54,
       72,   73,   82,  146,  167,  148,   69,   70,   74,  151,
       54,  149,   55,   54,   54,  152,   55,   54,  113,   82,
       54,  167,   54,   54,   54,  138,   54,   54,   54,  135,
       55,   54,  113,   83,   54,  113,   55,   54,   54,  357,
       54,   54,   72,   73,   54,  358,   54,   54,   69,   70,

       74,   54,  113,   55,   54,   83,  170,  170,  132,   84,
      171,   54,  168,   54,   54,   54,  124,   55,   54,  321,
       54,  169,   55,   54,   98,   54,  322,   54,   54,   95,
       54,  316,   54,   54,   69,   70,   75,   54,  169,   55,
       54,   54,   84,   55,   54,  316,   85,   54,  316,   54,
       54,   54,  428,   54,   54,  428,   54,  371,   55,   54,
      216,  216,  430,  372,  217,  316,   54,  428,   54,   54,
       69,   70,   75,  168,   54,  424,   55,   54,   54,   85,
       55,   54,  169,  426,   54,  429,   54,   54,   54,  425,
       54,   54,   54,  428,   55,   54,  423,  427,  106,  169,

      107,  422,   54,  421,   54,   54,   69,   70,   76,  108,
      420,   54,  419,   55,   54,   86,  218,  218,  316,  418,
      219,   54,  417,   54,   54,  416,  108,  415,   54,  414,
       55,   54,  316,  413,  412,  316,  411,  410,   54,  409,
       54,   54,   69,   70,   76,  408,  407,   54,  406,   55,
       54,   86,  316,  405,  404,  403,  402,   54,  401,   54,
       54,  400,  399,  398,   54,  397,   55,   54,  396,  395,
      394,  393,  392,  391,   54,  390,   54,   54,   69,   70,
       77,  389,  388,   54,  387,   55,   54,  386,  385,  384,
      383,  382,  381,   54,  380,   54,   54,  379,  378,  369,

       54,  369,   55,   54,  111,  111,  111,  111,  369,  111,
       54,  111,   54,   54,   69,   70,   77,  369,  369,  369,
      369,  377,  376,  375,  111,  111,  111,  111,  374,  111,
      373,  111,  370,  369,  368,  367,   54,  366,   55,   54,
      315,  315,  365,  364,  363,  315,   54,  362,   54,   54,
       69,   70,   78,  361,  288,  360,  359,  356,  289,  355,
      315,  315,  354,  290,  353,  315,  352,  351,  350,  349,
      348,  288,   54,  347,   55,   54,  315,  315,  289,  346,
      345,  315,   54,  290,   54,   54,   69,   70,   78,  344,
      343,  342,  341,  340,  339,  338,  315,  315,  337,  336,

      335,  315,  334,  333,  332,  331,  330,  329,   54,  328,
       55,   54,  327,  326,  325,  324,  323,  320,   54,  319,
       54,   54,   69,   70,   79,  318,  317,  313,  312,  311,
      310,  284,  309,  284,  308,  284,  307,  284,  306,  284,
      305,  284,  304,  284,   54,  303,   55,   54,  302,  301,
      300,  299,  298,  297,   54,  296,   54,   54,   69,   70,
       79,  295,  294,  293,  292,  291,  287,  286,  285,  284,
      283,  282,  281,  280,  279,  278,  277,  276,  275,  274,
       54,  273,   55,   54,  272,  271,  270,  269,  268,  267,
       54,  266,   54,   54,  110,  265,  110,  264,  263,  110,

      262,  110,  110,  110,  261,  110,  260,  259,  258,  257,
      256,  110,  255,  110,  219,  219,  217,  217,  254,  110,
      253,  110,  110,  110,  252,  110,  314,  251,  314,  250,
      249,  314,  248,  314,  314,  314,  247,  314,  246,  245,
      244,  243,  242,  314,  241,  314,  240,  239,  238,  237,
      236,  314,  235,  314,  314,  314,  234,  314,   66,   66,
       66,   66,   66,   66,   66,   66,   87,   87,   87,   87,
       87,   87,   87,   87,   90,   90,   90,   90,   90,   90,
       90,   90,   92,   92,   92,   92,   92,   92,   92,   92,
      102,  233,  232,  231,  102,  109,  109,  122,  230,  229,

      122,  122,  122,  122,  122,  153,  153,  228,  153,  153,
      227,  153,  153,  154,  154,  226,  154,  154,  154,  154,
      154,  157,  157,  225,  157,  157,  157,  157,  157,  158,
      158,  158,  158,  224,  158,  158,  158,  159,  159,  162,
      162,  166,  166,  181,  181,  190,  190,  193,  193,  196,
      196,  199,  199,  202,  202,  205,  205,  208,  208,  223,
      222,  221,  220,  171,  171,  215,  214,  213,  212,  211,
      210,  209,  207,  206,  204,  203,  201,  200,  198,  197,
      195,  194,  192,  191,  189,  188,  187,  186,  185,  182,
      123,  180,  179,  178,  177,  176,  175,  174,  173,  172,

      165,  164,  163,  161,  160,   94,  131,  130,  129,  128,
      127,  123,  121,  120,  119,  118,  117,  116,  112,  103,
      101,   94,  431,   93,   93,   91,   91,   41,  431,  431,
      431,  431,  431,  431,  431,  431,  431,  431,  431,  431,
      431,  431,  431,  431,  431,  431,  431,  431,  431,  431,
      431,  431,  431,  431,  431,  431,  431,  431,  431,  431,
      431,  431,  431,  431,  431,  431,  431,  431,  431,  431,
      431,  431,  431,  431,  431,  431,  431,  431,  431,  431,
      431,  431,  431,  431
    } ;

static yyconst flex_int16_t yy_chk[885] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    3,    3,    4,    4,
        5,  448,    5,    5,    6,   35,    6,    6,   47,   36,
        5,   35,    5,    5,    6,   36,    6,    6,    7,    7,
        7,   46,   50,   71,   47,   21,   50,   46,   59,   22,
       51,   58,   51,   80,  126,   59,  447,   71,   81,   80,

        7,   51,    7,    7,   81,   58,  126,   89,   58,  446,
        7,   89,    7,    7,    8,    8,    8,   21,   51,   21,
       21,   22,  154,   22,   22,   58,  154,   21,   23,   21,
       21,   22,   24,   22,   22,   82,    8,   83,    8,    8,
      155,   82,  445,   83,  155,  103,    8,   84,    8,    8,
        9,    9,   25,   84,  103,   85,    9,    9,    9,   86,
       23,   85,   23,   23,   24,   86,   24,   24,  113,   26,
       23,  103,   23,   23,   24,  444,   24,   24,    9,  443,
        9,    9,  113,   27,   25,  113,   25,   25,    9,  341,
        9,    9,   10,   10,   25,  341,   25,   25,   10,   10,

       10,   26,  113,   26,   26,   28,  108,  108,  442,   29,
      108,   26,  106,   26,   26,   27,  441,   27,   27,  297,
       10,  106,   10,   10,  437,   27,  297,   27,   27,  436,
       10,  290,   10,   10,   11,   11,   11,   28,  106,   28,
       28,   29,   30,   29,   29,  290,   31,   28,  290,   28,
       28,   29,  430,   29,   29,  429,   11,  356,   11,   11,
      167,  167,  427,  356,  167,  290,   11,  426,   11,   11,
       12,   12,   12,  168,   30,  422,   30,   30,   31,   32,
       31,   31,  168,  423,   30,  425,   30,   30,   31,  422,
       31,   31,   12,  424,   12,   12,  421,  423,  107,  168,

      107,  420,   12,  419,   12,   12,   13,   13,   13,  107,
      418,   32,  417,   32,   32,   33,  169,  169,  316,  416,
      169,   32,  415,   32,   32,  414,  107,  413,   13,  412,
       13,   13,  316,  411,  410,  316,  409,  407,   13,  405,
       13,   13,   14,   14,   14,  404,  403,   33,  402,   33,
       33,   34,  316,  401,  400,  399,  398,   33,  397,   33,
       33,  396,  395,  394,   14,  393,   14,   14,  392,  389,
      388,  387,  386,  385,   14,  384,   14,   14,   15,   15,
       15,  382,  381,   34,  380,   34,   34,  379,  377,  376,
      375,  374,  373,   34,  372,   34,   34,  371,  370,  368,

       15,  367,   15,   15,   56,   56,  111,  111,  366,   56,
       15,  111,   15,   15,   16,   16,   16,  365,  364,  363,
      362,  361,  360,  359,   56,   56,  111,  111,  358,   56,
      357,  111,  355,  353,  352,  351,   16,  350,   16,   16,
      289,  289,  349,  348,  347,  289,   16,  346,   16,   16,
       17,   17,   17,  345,  255,  344,  343,  340,  255,  339,
      289,  289,  336,  255,  335,  289,  334,  333,  332,  331,
      330,  255,   17,  329,   17,   17,  315,  315,  255,  328,
      327,  315,   17,  255,   17,   17,   18,   18,   18,  326,
      325,  323,  322,  321,  319,  313,  315,  315,  312,  311,

      310,  315,  309,  308,  307,  306,  305,  304,   18,  303,
       18,   18,  302,  301,  300,  299,  298,  296,   18,  295,
       18,   18,   19,   19,   19,  293,  291,  287,  286,  285,
      283,  282,  281,  280,  279,  278,  277,  276,  275,  274,
      273,  272,  271,  270,   19,  269,   19,   19,  268,  267,
      266,  265,  264,  263,   19,  262,   19,   19,   20,   20,
       20,  261,  260,  259,  258,  256,  254,  253,  252,  251,
      250,  249,  248,  247,  246,  245,  244,  243,  242,  241,
       20,  240,   20,   20,  239,  238,  237,  236,  235,  234,
       20,  233,   20,   20,   55,  232,   55,  231,  230,   55,

      229,   55,   55,   55,  228,   55,  226,  225,  223,  222,
      221,   55,  220,   55,  219,  218,  217,  216,  215,   55,
      214,   55,   55,   55,  213,   55,  288,  212,  288,  211,
      210,  288,  209,  288,  288,  288,  207,  288,  206,  204,
      203,  201,  200,  288,  198,  288,  197,  195,  194,  192,
      191,  288,  189,  288,  288,  288,  188,  288,  432,  432,
      432,  432,  432,  432,  432,  432,  433,  433,  433,  433,
      433,  433,  433,  433,  434,  434,  434,  434,  434,  434,
      434,  434,  435,  435,  435,  435,  435,  435,  435,  435,
      438,  187,  186,  185,  438,  439,  439,  440,  184,  183,

      440,  440,  440,  440,  440,  449,  449,  182,  449,  449,
      179,  449,  449,  450,  450,  178,  450,  450,  450,  450,
      450,  451,  451,  177,  451,  451,  451,  451,  451,  452,
      452,  452,  452,  176,  452,  452,  452,  453,  453,  454,
      454,  455,  455,  456,  456,  457,  457,  458,  458,  459,
      459,  460,  460,  461,  461,  462,  462,  463,  463,  175,
      174,  173,  172,  171,  170,  165,  164,  163,  161,  160,
      152,  151,  149,  148,  146,  145,  143,  142,  140,  139,
      137,  136,  134,  133,  131,  130,  129,  128,  127,  125,
      123,  121,  120,  119,  118,  117,  116,  115,  114,  112,

      101,  100,   99,   97,   96,   94,   78,   77,   76,   75,
       74,   67,   65,   64,   63,   62,   61,   60,   57,   49,
       48,   43,   41,   40,   39,   38,   37,  431,  431,  431,
      431,  431,  431,  431,  431,  431,  431,  431,  431,  431,
      431,  431,  431,  431,  431,  431,  431,  431,  431,  431,
      431,  431,  431,  431,  431,  431,  431,  431,  431,  431,
      431,  431,  431,  431,  431,  431,  431,  431,  431,  431,
      431,  431,  431,  431,  431,  431,  431,  431,  431,  431,
      431,  431,  431,  431
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "glb_lexer.l"
/* GLoBES -- General LOng Baseline Experiment Simulator
 * (C) 2002 - 2007,  The GLoBES Team
 *
 * GLoBES is mainly intended for academic purposes. Proper
 * credit must be given if you use GLoBES or parts of it. Please
 * read the section 'Credit' in the README file.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */
#define YY_NO_UNISTD_H 1
/* This here caused an unpleasant problem:
 * things like
 * %s rule
 * would cause a
 * #define rule xxx
 * statement in glb_lexer.c and that in turn causes
 * trouble with inlcude files which contain
 * glbXXX(int rule)
 * because this will be expanded by the preprocessor to
 * glbXXX(int xxx)
 * which then causes a stupid error of the form
 * parse error before numeric constant
 * The flex manual says that these things have global scope
 * but as usual I read the manual after the fact
 * PH
 */




















#line 75 "glb_lexer.l"
/* need this for the call to atof() below */
#include <math.h>
#include <string.h>

#include "glb_parser_type.h"
#include "glb_parser.h"
#include "glb_error.h"


 #define MAX_INCLUDE_DEPTH 10
static YY_BUFFER_STATE include_stack[MAX_INCLUDE_DEPTH];
static int include_stack_ptr = 0;
int glb_line_num=1;
char *glb_file_id;
static int line_buf[MAX_INCLUDE_DEPTH];
static char *file_name_buf[MAX_INCLUDE_DEPTH];
static int cond_buf;
/* I am not sure wether this works with nested contexts */
static int cond_buf_i;
static int cond_buf_str;
static char *fnbuf;
static size_t len;

void glb_lexer_cleanup();

// JK, 2010-09-26
// We now allow any character except '"' inside strings to allow for
// multi-line citation information
//FN       [a-zA-Z0-9./][a-zA-Z0-9_./-]*


#line 892 "glb_lexer.c"

#define INITIAL 0
#define glb_lexer_incl 1
#define glb_lexer_grp 2
#define glb_lexer_rule 3
#define glb_lexer_chl 4
#define glb_lexer_energy 5
#define glb_lexer_cross 6
#define glb_lexer_flux 7
#define glb_lexer_nuflux 8
#define glb_lexer_sys 9
#define glb_lexer_defr 10
#define glb_lexer_defc 11
#define glb_lexer_defe 12
#define glb_lexer_defx 13
#define glb_lexer_deff 14
#define glb_lexer_defnf 15
#define glb_lexer_defsys 16
#define glb_lexer_comment 17
#define glb_lexer_linecomment 18
#define glb_lexer_str 19

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

int yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 119 "glb_lexer.l"


#line 1096 "glb_lexer.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 432 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 828 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 121 "glb_lexer.l"
{cond_buf=YY_START; BEGIN(glb_lexer_linecomment);}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 122 "glb_lexer.l"
/* eat anything that's not a line break */
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 123 "glb_lexer.l"
{ ++glb_line_num; BEGIN(cond_buf); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 125 "glb_lexer.l"
{cond_buf=YY_START;BEGIN(glb_lexer_comment);}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 126 "glb_lexer.l"
/* eat anything that's not a '*' */
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 127 "glb_lexer.l"
/* eat up '*'s not followed by '/'s */
	YY_BREAK
case 7:
/* rule 7 can match eol */
YY_RULE_SETUP
#line 128 "glb_lexer.l"
++glb_line_num;
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 129 "glb_lexer.l"
BEGIN(cond_buf);
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 132 "glb_lexer.l"
{
  yylval.in = -1;
  return ENDEXP;
}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 137 "glb_lexer.l"
{
  yylval.in = -1;
  return ENDDET;
}
	YY_BREAK

case 11:
YY_RULE_SETUP
#line 145 "glb_lexer.l"
{BEGIN(glb_lexer_defr);yylval.name=strdup(yytext);return GID;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 146 "glb_lexer.l"
{BEGIN(glb_lexer_defc);yylval.name=strdup(yytext);return GID;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 147 "glb_lexer.l"
{BEGIN(glb_lexer_defe);yylval.name=strdup(yytext);return GID;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 148 "glb_lexer.l"
{BEGIN(glb_lexer_defx);yylval.name=strdup(yytext);return GID;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 149 "glb_lexer.l"
{BEGIN(glb_lexer_deff);yylval.name=strdup(yytext);return GID;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 150 "glb_lexer.l"
{BEGIN(glb_lexer_defnf);yylval.name=strdup(yytext);return GID;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 151 "glb_lexer.l"
{BEGIN(glb_lexer_defsys);yylval.name=strdup(yytext);return GID;}
	YY_BREAK

case 18:
YY_RULE_SETUP
#line 154 "glb_lexer.l"
{cond_buf_i=YY_START;BEGIN(glb_lexer_incl);}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 156 "glb_lexer.l"
/* eat the whitespace */
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 157 "glb_lexer.l"
{ /* got the include file name */
  if (include_stack_ptr >= MAX_INCLUDE_DEPTH)
  {
    fprintf( stderr, "FATAL: Includes nested too deeply\n" );
    exit( 1 );
  }

// This code rewritten by JK on Mar 30, 2010
//if(include_stack_ptr==0)
//{
//file_name_buf[include_stack_ptr]=glb_file_id;
//line_buf[include_stack_ptr]=glb_line_num;
//}
//
//include_stack[include_stack_ptr++] =
//YY_CURRENT_BUFFER;
//
//fnbuf=strdup(yytext);
//len=strlen(fnbuf);
//if(fnbuf[len-1]!='\"') {fprintf(stderr,"FATAL:"
//" Unterminated filename\n");exit(1) ;}
//if(fnbuf[0]!='\"') {fprintf(stderr,"FATAL:"
//" Unquoted filename\n");exit(1) ;}
//fnbuf2=(char *) glb_malloc((len-1)*sizeof(char));
//for(i=0;i<len-1;i++) fnbuf2[i]=fnbuf[i+1];
//fnbuf2[len-2]='\0';
//yyin = glb_fopen( fnbuf2, "r" );
//
//if ( ! yyin ){
//fprintf(stderr,"FATAL: Could not open file %s\n",fnbuf2);exit(1);}
//
//file_name_buf[include_stack_ptr]=(char*) strdup(fnbuf2);
//glb_file_id=file_name_buf[include_stack_ptr];
//line_buf[include_stack_ptr]=glb_line_num;
//glb_line_num=0;
//glb_free(fnbuf);
//glb_free(fnbuf2);

  /* Remember status of the including file */
  include_stack[include_stack_ptr] = YY_CURRENT_BUFFER;
  file_name_buf[include_stack_ptr] = glb_file_id;
  line_buf[include_stack_ptr]      = glb_line_num;

  /* Remove quotes from filename */
  fnbuf = strdup(yytext);
  len   = strlen(fnbuf);
  if (fnbuf[len-1] != '\"') { fprintf(stderr,"FATAL: Unterminated filename: %s\n", fnbuf); exit(1); }
  if (fnbuf[0] != '\"')     { fprintf(stderr,"FATAL: Unquoted filename: %s\n", fnbuf);     exit(1); }
  glb_file_id = (char *) glb_malloc((len-1)*sizeof(char));
  strncpy(glb_file_id, fnbuf+1, len-2);
  glb_file_id[len-2] = '\0';
  glb_free(fnbuf);

  /* Open included file and re-initialize status variables */
  yyin = glb_fopen(glb_file_id, "r");
  if (!yyin )  { fprintf(stderr,"FATAL: Could not open file %s\n",glb_file_id); exit(1); }
  glb_line_num = 0;
  include_stack_ptr++;
  yy_switch_to_buffer(yy_create_buffer(yyin,YY_BUF_SIZE));
  BEGIN(cond_buf_i);
}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(glb_lexer_incl):
case YY_STATE_EOF(glb_lexer_grp):
case YY_STATE_EOF(glb_lexer_rule):
case YY_STATE_EOF(glb_lexer_chl):
case YY_STATE_EOF(glb_lexer_energy):
case YY_STATE_EOF(glb_lexer_cross):
case YY_STATE_EOF(glb_lexer_flux):
case YY_STATE_EOF(glb_lexer_nuflux):
case YY_STATE_EOF(glb_lexer_sys):
case YY_STATE_EOF(glb_lexer_defr):
case YY_STATE_EOF(glb_lexer_defc):
case YY_STATE_EOF(glb_lexer_defe):
case YY_STATE_EOF(glb_lexer_defx):
case YY_STATE_EOF(glb_lexer_deff):
case YY_STATE_EOF(glb_lexer_defnf):
case YY_STATE_EOF(glb_lexer_defsys):
case YY_STATE_EOF(glb_lexer_comment):
case YY_STATE_EOF(glb_lexer_linecomment):
case YY_STATE_EOF(glb_lexer_str):
#line 221 "glb_lexer.l"
{
  if (--include_stack_ptr < 0)  /* If top level buffer ends, we're done */
  {
/*JK 2011-12-29 This would have potentially disregarded the last line in the file
    glb_copy_buff();
    glbReset();*/

    /* BUGFIX #9 -- This lines fixes a tricky bug in the parser */
    include_stack_ptr = 0;
    yyterminate();
  }
  else                          /* Otherwise, switch back to previous buffer */
  {
    glb_fclose(yyin);
    yy_delete_buffer(YY_CURRENT_BUFFER);
    yy_switch_to_buffer(include_stack[include_stack_ptr]);
    glb_line_num = line_buf[include_stack_ptr];
    glb_free(glb_file_id);
    glb_file_id  = file_name_buf[include_stack_ptr];
  }
}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 244 "glb_lexer.l"
{
yylval.in=-1;
return GRPOPEN;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 248 "glb_lexer.l"
{
yylval.name=strdup(yytext);

return CHANNEL;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 253 "glb_lexer.l"
{yylval.in=+1;return PM;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 254 "glb_lexer.l"
{yylval.in=-1;return PM;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 256 "glb_lexer.l"
{yylval.in=1;return FLAVOR;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 257 "glb_lexer.l"
{yylval.in=2;return FLAVOR;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 258 "glb_lexer.l"
{yylval.in=3;return FLAVOR;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 260 "glb_lexer.l"
{yylval.in=11;return FLAVOR;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 261 "glb_lexer.l"
{yylval.in=12;return FLAVOR;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 262 "glb_lexer.l"
{yylval.in=13;return FLAVOR;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 265 "glb_lexer.l"
{
yylval.name=strdup(yytext);

return ENERGY;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 270 "glb_lexer.l"
{
yylval.name=strdup(yytext);

return SIGNAL;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 275 "glb_lexer.l"
{
yylval.name=strdup(yytext);

return BG;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 280 "glb_lexer.l"
{
yylval.name=strdup(yytext);
return SYS_ON_FUNCTION;
}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 285 "glb_lexer.l"
{
yylval.name=strdup(yytext);
return SYS_OFF_FUNCTION;
}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 290 "glb_lexer.l"
{
yylval.name=strdup(yytext);
return SYS_MULTIEX_ERRORS;
}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 297 "glb_lexer.l"
{cond_buf_str=YY_START;BEGIN(glb_lexer_str);}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 299 "glb_lexer.l"
{BEGIN(cond_buf_str);}
	YY_BREAK
/* JK 2010-09-26
    <glb_lexer_str>\n {glb_fatal("Lexer error: Unterminated string");exit(1);}
 */;
case 39:
/* rule 39 can match eol */
YY_RULE_SETUP
#line 305 "glb_lexer.l"
{
yylval.name=strdup(yytext);
return FNAME;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 309 "glb_lexer.l"
{
yylval.name=strdup(yytext);
return VERS;
}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 314 "glb_lexer.l"
{
yylval.name=strdup(yytext);
return VERS;
}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 319 "glb_lexer.l"
{
yylval.name=strdup(yytext);
return CROSS;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 323 "glb_lexer.l"
{
yylval.name=strdup(yytext);
return FLUXP;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 328 "glb_lexer.l"
{
yylval.name=strdup(yytext);
return FLUXM;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 335 "glb_lexer.l"
{
yylval.name=strdup(yytext);
return NUFLUX;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 340 "glb_lexer.l"
{
yylval.name=strdup(yytext);
return NUFLUX;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 344 "glb_lexer.l"
{return RULESEP;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 345 "glb_lexer.l"
{return RULEMULT;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 349 "glb_lexer.l"
{glb_namerec *s;
s = glb_getname (yytext,"rule");
if (s == 0)
s = glb_putname (yytext,"rule",NAME);
BEGIN(INITIAL);
BEGIN(glb_lexer_rule);
if(strcmp(s->context,"rule")!=0)
{yylval.nameptr=s;return RDF;}

yylval.nameptr = s;

return s->type;
}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 363 "glb_lexer.l"
{glb_namerec *s;
s = glb_getname (yytext,"channel");
if (s == 0)
s = glb_putname (yytext,"channel",NAME);
BEGIN(INITIAL);
BEGIN(glb_lexer_chl);
if(strcmp(s->context,"channel")!=0)
{yylval.nameptr=s;return RDF;}

yylval.nameptr = s;

return s->type;
}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 377 "glb_lexer.l"
{glb_namerec *s;
s = glb_getname (yytext,"energy");
if (s == 0)
s = glb_putname (yytext,"energy",NAME);
BEGIN(INITIAL);
BEGIN(glb_lexer_energy);
if(strcmp(s->context,"energy")!=0)
{yylval.nameptr=s;return RDF;}

yylval.nameptr = s;

return s->type;
}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 391 "glb_lexer.l"
{glb_namerec *s;
s = glb_getname (yytext,"cross");
if (s == 0)
s = glb_putname (yytext,"cross",NAME);
BEGIN(INITIAL);
BEGIN(glb_lexer_cross);
if(strcmp(s->context,"cross")!=0)
{yylval.nameptr=s;return RDF;}

yylval.nameptr = s;

return s->type;
}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 406 "glb_lexer.l"
{glb_namerec *s;
s = glb_getname (yytext,"flux");
if (s == 0)
s = glb_putname (yytext,"flux",NAME);
BEGIN(INITIAL);
BEGIN(glb_lexer_flux);
if(strcmp(s->context,"flux")!=0)
{yylval.nameptr=s;return RDF;}

yylval.nameptr = s;

return s->type;
}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 420 "glb_lexer.l"
{glb_namerec *s;
s = glb_getname (yytext,"nuflux");
if (s == 0)
s = glb_putname (yytext,"nuflux",NAME);
BEGIN(INITIAL);
BEGIN(glb_lexer_nuflux);
if(strcmp(s->context,"nuflux")!=0)
{yylval.nameptr=s;return RDF;}

yylval.nameptr = s;

return s->type;
}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 434 "glb_lexer.l"
{
  glb_namerec *s = glb_getname(yytext,"sys");
  if (s == 0)  s = glb_putname(yytext,"sys",NAME);
  BEGIN(INITIAL);
  BEGIN(glb_lexer_sys);
  if(strcmp(s->context,"sys") != 0)
    { yylval.nameptr=s;return RDF; }
  yylval.nameptr = s;
  return s->type;
}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 445 "glb_lexer.l"
{glb_namerec *s;
s = glb_getname (yytext,"rule");
if (s == 0) { yylval.name=strdup(yytext); return NDEF; }
yylval.nameptr = s;
return s->type;
}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 452 "glb_lexer.l"
{
BEGIN(INITIAL);
yylval.in=-1;
return GRPCLOSE;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 458 "glb_lexer.l"
{
yylval.name=strdup(yytext);
return IDN;
}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 466 "glb_lexer.l"
{yylval.val=atof(yytext);
return NUM;
}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 470 "glb_lexer.l"
{yylval.name=strdup(yytext);return IDN;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 472 "glb_lexer.l"
{
yylval.val=atof(yytext);
return NUM;
}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 477 "glb_lexer.l"
{
 yylval.val=atof(yytext);
 return NUM;
}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 482 "glb_lexer.l"
{
yylval.val=atof(yytext);
return NUM;
}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 487 "glb_lexer.l"
{
yylval.val=atof(yytext);
return NUM;
}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 492 "glb_lexer.l"
{
yylval.val=atof(yytext);
return NUM;
}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 500 "glb_lexer.l"
{glb_symrec *s;
s = glb_getsym (yytext);
if (s == 0)
s = glb_putsym (yytext, VAR);
yylval.tptr = s;
return s->type;
}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 509 "glb_lexer.l"
{glb_symrec *s;
s = glb_getsym (yytext);
if (s == 0)
s = glb_putsym (yytext, LVAR);
yylval.tptr = s;
return s->type;
}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 521 "glb_lexer.l"
/* eat up whitespace */
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 523 "glb_lexer.l"
/* empty */
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 525 "glb_lexer.l"
return (int) yytext[0];
	YY_BREAK
case 71:
/* rule 71 can match eol */
YY_RULE_SETUP
#line 528 "glb_lexer.l"
/* yylloc.first_line++;*/ glb_line_num++; /*return '\n';*/
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 529 "glb_lexer.l"
ECHO;
	YY_BREAK
#line 1819 "glb_lexer.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 432 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 432 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 431);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 529 "glb_lexer.l"




/* OLD CODE, DOES NOT RUN WITH NEWER FLEX VERSIONS ANYMORE [WW, JK]:

void glb_lexer_cleanup() {
     if( yy_current_buffer != NULL )
     {
         yy_delete_buffer(yy_current_buffer );
         yy_current_buffer = 0;
     }
}
*/



void glb_lexer_cleanup() {
      if( YY_CURRENT_BUFFER != NULL )
          yy_delete_buffer(YY_CURRENT_BUFFER );
}



