/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/lin/globes/cvs-noaccess/Projects/GLOBES/Distribution/source/glb_lexer.c,v 1.4 2005/07/27 15:55:08 globes Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 58
#define YY_END_OF_BUFFER 59
static yyconst short int yy_accept[246] =
    {   0,
       54,   54,   13,   13,   54,   54,   54,   54,   54,   54,
       54,   54,   54,   54,   54,   54,   54,   54,   54,   54,
       54,   54,   54,   54,   54,   54,    2,    2,    0,    0,
       59,   56,   54,   57,   28,   56,   56,   56,   56,   56,
       46,   36,   37,   53,   19,   20,   53,   21,   53,   19,
       53,   53,   53,   14,   13,   58,   15,   44,   37,   17,
       18,   37,   37,   37,   37,   56,   56,   56,   56,   56,
        2,    4,    3,   30,   29,   31,   54,   43,   43,   47,
       47,    0,   49,    1,   48,   46,    0,   53,   19,   20,
       53,   21,   53,   53,   19,   53,   53,   53,   14,   13,

       45,   45,   45,   45,   45,   45,   45,   38,   38,   39,
       39,   40,   40,   41,   41,   42,   42,    2,    3,    3,
        5,   31,   43,   43,   47,   47,    0,    0,   48,    0,
        0,   52,   53,   53,   53,   19,   53,   53,   53,   45,
       45,   45,   45,   45,   45,   45,   38,   38,   39,   39,
       40,   40,   41,   41,   42,   42,   43,   47,    0,    0,
       51,    0,   50,   53,   53,   53,   19,   11,   53,    7,
       45,   45,   45,   45,   45,   45,   38,   39,   40,   41,
       42,   43,   47,    0,   53,   53,   10,   53,   53,   45,
       45,   45,   45,   45,   45,   38,   39,   40,   41,   42,

        6,   47,    0,   22,   23,   24,   53,    9,   53,   45,
       45,   45,   45,   45,   45,   47,    0,   22,   23,   24,
        8,   12,   45,   26,   45,   25,   45,   45,   32,   55,
       45,   16,   45,   45,   45,   45,   45,   45,   45,   34,
       27,   33,   45,   35,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    7,    8,    1,    1,    1,
        1,    9,   10,    1,   11,   12,   13,   14,   14,   14,
       14,   14,   14,   14,   14,   14,   14,   15,    1,   16,
        1,   17,    1,   18,   19,   20,   21,   22,   23,   22,
       24,   22,   22,   22,   22,   25,   26,   27,   28,   22,
       22,   29,   30,   31,   32,   22,   22,   33,   22,   22,
        1,    1,    1,    1,   34,    1,   35,   36,   37,   38,

       39,   40,   41,   42,   43,   22,   44,   45,   46,   47,
       48,   22,   22,   49,   50,   51,   52,   53,   22,   54,
       55,   22,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[56] =
    {   0,
        1,    2,    3,    1,    1,    1,    1,    1,    4,    1,
        5,    5,    5,    6,    1,    1,    1,    1,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    6,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7
    } ;

static yyconst short int yy_base[270] =
    {   0,
        0,    0,   54,   56,   23,   27,   52,   57,   97,  137,
       63,   93,  101,  141,  145,  152,  158,  165,  169,  173,
      187,  193,  209,  213,  217,  228,   62,   74,  277,  311,
      537,  538,  534,  538,  538,  508,  481,  529,  518,  522,
       81,  538,  538,    0,  325,   97,  502,  168,   36,  482,
      483,  480,  474,    0,  523,  538,  538,  538,   48,  538,
      538,  487,  484,  485,  481,  493,  492,  491,  490,  489,
        0,  538,   73,  538,  538,    0,  513,    0,  491,    0,
      474,  488,  112,  538,  202,  284,  117,    0,    0,  212,
      481,  305,  475,  461,  469,  455,  469,  460,    0,  502,

        0,  468,  459,  459,  453,  450,  453,    0,  474,    0,
      473,    0,  472,    0,  471,    0,  470,    0,  130,  143,
      538,    0,    0,  459,    0,  442,  465,  259,  224,  261,
      475,  474,  466,  439,  435,  435,  429,  414,  414,    0,
      415,  404,  409,  379,  369,  363,    0,  380,    0,  375,
        0,  373,    0,  367,    0,  365,  366,  332,  332,  364,
      361,  355,  353,  332,  318,  311,  319,    0,  307,    0,
      305,  300,  297,  293,  291,  285,  305,  303,  302,  301,
      300,  324,  282,  290,  312,  270,    0,  253,  268,  264,
      269,  256,  261,  251,  266,  293,  291,  285,  284,  283,

      538,  228,  251,  356,  362,  336,  216,    0,  216,  202,
      200,  204,  182,  201,  191,  182,  198,    0,  364,  367,
        0,    0,  173,    0,  172,    0,  171,  153,    0,  538,
      136,    0,  140,  128,  125,  122,  127,  127,  121,   89,
        0,    0,   76,    0,  538,  419,  426,  433,  114,  109,
      435,  442,   98,   92,   83,   81,   80,   54,  449,  456,
      459,  461,  463,  465,  467,  469,  471,  473,  475
    } ;

static yyconst short int yy_def[270] =
    {   0,
      245,    1,  246,  246,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,  247,  247,  248,  248,
      245,  245,  245,  245,  245,  249,  250,  245,  245,  245,
      245,  245,  245,  251,  251,  251,  251,  251,  251,   45,
      251,  251,  251,  252,  245,  245,  245,  245,  253,  245,
      245,  253,  253,  253,  253,  254,  255,  256,  257,  258,
      259,  245,  260,  245,  245,  261,  245,  262,  262,  263,
      263,  245,  245,  245,  245,  245,  245,  251,   45,  251,
      251,  251,  251,  251,   45,  251,  251,  251,  252,  245,

      264,  264,  264,  264,  264,  264,  264,  265,  265,  266,
      266,  267,  267,  268,  268,  269,  269,  259,  260,  260,
      245,  261,  262,  262,  263,  263,  245,  245,  245,  245,
      245,  245,  251,  251,  251,   45,  251,  251,  251,  264,
      264,  264,  264,  264,  264,  264,  265,  265,  266,  266,
      267,  267,  268,  268,  269,  269,  262,  263,  245,  245,
      245,  245,  245,  251,  251,  251,   45,  251,  251,  251,
      264,  264,  264,  264,  264,  264,  265,  266,  267,  268,
      269,  262,  263,  245,  251,  251,  251,  251,  251,  264,
      264,  264,  264,  264,  264,  265,  266,  267,  268,  269,

      245,  263,  245,  251,  251,  251,  251,  251,  251,  264,
      264,  264,  264,  264,  264,  263,  245,  204,  251,  251,
      251,  251,  264,  264,  264,  264,  264,  264,  263,  245,
      264,  264,  264,  264,  264,  264,  264,  264,  264,  264,
      264,  264,  264,  264,    0,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245
    } ;

static yyconst short int yy_nxt[594] =
    {   0,
       32,   33,   34,   32,   35,   36,   37,   38,   32,   32,
       32,   39,   40,   41,   42,   32,   32,   43,   44,   44,
       44,   44,   45,   44,   44,   46,   47,   44,   44,   44,
       48,   44,   44,   32,   44,   44,   49,   44,   50,   51,
       44,   44,   52,   44,   44,   46,   44,   44,   53,   44,
       48,   44,   44,   44,   44,   55,   56,   55,   56,   44,
      116,   45,   44,   44,   72,   45,   44,   57,   58,   59,
       73,   44,   57,   58,   59,   44,   72,   93,   57,   58,
       63,  120,   73,  102,   94,  121,  114,  112,   44,  110,
       45,   44,   85,   44,   86,   45,   44,  103,  108,   44,

       44,   45,   44,   87,  101,   44,   60,   61,   57,   58,
       63,   44,   57,   58,   62,   80,   57,   58,   64,   87,
       78,  244,  243,   90,   90,   83,  131,  131,   90,   44,
      132,   45,   44,   44,  128,   45,   44,   44,  245,   45,
       44,   44,  245,   90,   90,   44,   60,   61,   90,   44,
      128,  120,   57,   58,   62,  121,   57,   58,   64,  242,
       57,   58,   65,   66,  241,  240,  239,   57,   58,   65,
       66,  238,  237,   44,   67,   45,   44,   44,   67,   45,
       44,   44,  236,   45,   44,   44,   92,  235,   44,   44,
       45,   44,   68,   44,   44,  234,   45,   44,   68,   92,

       44,   44,   92,   45,   44,   44,   44,   45,   44,   44,
      233,   45,   44,   44,   69,  129,  232,   44,   69,   92,
      231,   44,   70,   44,  130,   45,   44,  230,  229,   44,
      228,   45,   44,   70,  227,   44,  226,  129,   90,   90,
      130,   44,  225,   90,  224,   44,  130,   45,   44,   44,
      223,   45,   44,   44,  222,   45,   44,   44,   90,   90,
      221,   44,  130,   90,   44,   44,   45,   44,  160,  160,
      162,  162,  161,  217,  163,  216,   44,   56,   56,   74,
       56,   75,   56,   56,   56,   56,   56,   56,  201,  201,
      201,   56,   56,   56,   56,   85,  201,   86,  201,  215,

      214,  213,  212,  211,  210,  209,   87,  208,  207,  203,
       56,   56,   56,   74,   56,   75,   56,   56,   56,   56,
       56,   56,   87,   92,  202,   56,   56,   56,   56,  201,
      200,  199,  198,  197,  204,  196,   92,  205,  195,   92,
      194,  193,  206,  192,   56,   89,  191,   89,  190,   89,
      204,   89,   89,   89,  220,   89,   92,  205,  189,  188,
      187,   89,  206,   89,  186,  185,  163,  220,  163,   89,
      220,   89,   89,   89,  161,   89,  218,  161,  218,  184,
      218,  183,  218,  218,  218,  220,  218,  220,  219,  219,
      219,  219,  218,  219,  218,  219,  182,  181,  220,  180,

      218,  220,  218,  218,  218,  179,  218,  178,  219,  219,
      219,  219,  177,  219,  176,  219,  175,  174,  220,   54,
       54,   54,   54,   54,   54,   54,   71,   71,   71,   71,
       71,   71,   71,   76,   76,   76,   76,   76,   76,   76,
       88,   88,   99,  173,  172,   99,   99,   99,   99,  118,
      118,  171,  170,  118,  118,  118,  119,  119,  169,  119,
      119,  119,  119,  122,  122,  122,  123,  123,  125,  125,
      140,  140,  147,  147,  149,  149,  151,  151,  153,  153,
      155,  155,  168,  167,  166,  165,  164,  132,  132,  159,
      158,  157,  156,  154,  152,  150,  148,  146,  145,  144,

      143,  142,  141,  100,  139,  138,  137,  136,  135,  134,
      133,  127,  126,  124,   77,  117,  115,  113,  111,  109,
      107,  106,  105,  104,  100,   98,   97,   96,   95,   91,
       84,   83,   82,   81,   79,   77,  245,   31,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245

    } ;

static yyconst short int yy_chk[594] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    3,    3,    4,    4,    5,
      258,    5,    5,    6,   27,    6,    6,    7,    7,    7,
       27,    5,    8,    8,    8,    6,   28,   49,   11,   11,
       11,   73,   28,   59,   49,   73,  257,  256,    7,  255,
        7,    7,   41,    8,   41,    8,    8,   59,  254,   11,

        7,   11,   11,   41,  253,    8,    9,    9,   12,   12,
       12,   11,    9,    9,    9,  250,   13,   13,   13,   41,
      249,  243,  240,   46,   46,   83,   87,   87,   46,   12,
       87,   12,   12,    9,   83,    9,    9,   13,  119,   13,
       13,   12,  119,   46,   46,    9,   10,   10,   46,   13,
       83,  120,   10,   10,   10,  120,   14,   14,   14,  239,
       15,   15,   15,   17,  238,  237,  236,   16,   16,   16,
       18,  235,  234,   10,   19,   10,   10,   14,   20,   14,
       14,   15,  233,   15,   15,   10,   48,  231,   16,   14,
       16,   16,   21,   15,   17,  228,   17,   17,   22,   48,

       16,   18,   48,   18,   18,   19,   17,   19,   19,   20,
      227,   20,   20,   18,   23,   85,  225,   19,   24,   48,
      223,   20,   25,   21,   85,   21,   21,  217,  216,   22,
      215,   22,   22,   26,  214,   21,  213,  129,   90,   90,
       85,   22,  212,   90,  211,   23,  129,   23,   23,   24,
      210,   24,   24,   25,  209,   25,   25,   23,   90,   90,
      207,   24,  129,   90,   26,   25,   26,   26,  128,  128,
      130,  130,  128,  203,  130,  202,   26,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   29,   29,  200,  199,
      198,   29,   29,   29,   29,   86,  197,   86,  196,  195,

      194,  193,  192,  191,  190,  189,   86,  188,  186,  184,
       29,   30,   30,   30,   30,   30,   30,   30,   30,   30,
       30,   30,   86,   92,  183,   30,   30,   30,   30,  182,
      181,  180,  179,  178,  185,  177,   92,  185,  176,   92,
      175,  174,  185,  173,   30,   45,  172,   45,  171,   45,
      185,   45,   45,   45,  206,   45,   92,  185,  169,  167,
      166,   45,  185,   45,  165,  164,  163,  206,  162,   45,
      206,   45,   45,   45,  161,   45,  204,  160,  204,  159,
      204,  158,  204,  204,  204,  220,  204,  206,  205,  205,
      219,  219,  204,  205,  204,  219,  157,  156,  220,  154,

      204,  220,  204,  204,  204,  152,  204,  150,  205,  205,
      219,  219,  148,  205,  146,  219,  145,  144,  220,  246,
      246,  246,  246,  246,  246,  246,  247,  247,  247,  247,
      247,  247,  247,  248,  248,  248,  248,  248,  248,  248,
      251,  251,  252,  143,  142,  252,  252,  252,  252,  259,
      259,  141,  139,  259,  259,  259,  260,  260,  138,  260,
      260,  260,  260,  261,  261,  261,  262,  262,  263,  263,
      264,  264,  265,  265,  266,  266,  267,  267,  268,  268,
      269,  269,  137,  136,  135,  134,  133,  132,  131,  127,
      126,  124,  117,  115,  113,  111,  109,  107,  106,  105,

      104,  103,  102,  100,   98,   97,   96,   95,   94,   93,
       91,   82,   81,   79,   77,   70,   69,   68,   67,   66,
       65,   64,   63,   62,   55,   53,   52,   51,   50,   47,
       40,   39,   38,   37,   36,   33,   31,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245

    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "glb_lexer.l"
#define INITIAL 0
/* GLoBES -- General LOng Baseline Experiment Simulator
 * (C) 2002 - 2004,  The GLoBES Team
 *
 * GLoBES is mainly intended for academic purposes. Proper
 * credit must be given if you use GLoBES or parts of it. Please
 * read the section 'Credit' in the README file.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */
#define incl 1

#define grp 2

#define rule 3

#define chl 4

#define energy 5

#define cross 6

#define flux 7

#define defr 8

#define defc 9

#define defe 10

#define defx 11

#define deff 12

#define comment 13

#define str 14

#line 47 "glb_lexer.l"
/* need this for the call to atof() below */
#include <math.h>
#include <string.h>

#include "glb_parser_type.h"
#include "glb_parser.h"
#include "glb_error.h"


 #define MAX_INCLUDE_DEPTH 10
static YY_BUFFER_STATE include_stack[MAX_INCLUDE_DEPTH];
static int include_stack_ptr = 0;
int glb_line_num=0;
char *glb_file_id;
static int line_buf[MAX_INCLUDE_DEPTH];
static char *file_name_buf[MAX_INCLUDE_DEPTH];
static int cond_buf; 
/* I am not sure wether this works with nested contexts */
static int cond_buf_i; 
static int cond_buf_str; 
static char *fnbuf,*fnbuf2;
static size_t len,i;

void glb_lexer_cleanup();


#line 659 "glb_lexer.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 84 "glb_lexer.l"


  

#line 815 "glb_lexer.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 246 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 538 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 88 "glb_lexer.l"
{cond_buf=YY_START;BEGIN(comment);}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 90 "glb_lexer.l"
/* eat anything that's not a '*' */
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 91 "glb_lexer.l"
/* eat up '*'s not followed by '/'s */
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 92 "glb_lexer.l"
++glb_line_num;
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 93 "glb_lexer.l"
BEGIN(cond_buf);
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 95 "glb_lexer.l"
{
glb_copy_buff();
glbReset();
}
	YY_BREAK

case 7:
YY_RULE_SETUP
#line 102 "glb_lexer.l"
{BEGIN(defr);yylval.name=yytext;return GID;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 103 "glb_lexer.l"
{BEGIN(defc);yylval.name=yytext;return GID;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 104 "glb_lexer.l"
{BEGIN(defe);yylval.name=yytext;return GID;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 105 "glb_lexer.l"
{BEGIN(defx);yylval.name=yytext;return GID;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 106 "glb_lexer.l"
{BEGIN(deff);yylval.name=yytext;return GID;}
	YY_BREAK

case 12:
YY_RULE_SETUP
#line 109 "glb_lexer.l"
{cond_buf_i=YY_START;BEGIN(incl);}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 111 "glb_lexer.l"
/* eat the whitespace */
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 112 "glb_lexer.l"
{ /* got the include file name */
if ( include_stack_ptr >= MAX_INCLUDE_DEPTH )
{
fprintf( stderr, "FATAL: Includes nested too deeply\n" );
exit( 1 );
}

if(include_stack_ptr==0) 
{
file_name_buf[include_stack_ptr]=glb_file_id;
line_buf[include_stack_ptr]=glb_line_num;
}



include_stack[include_stack_ptr++] =
YY_CURRENT_BUFFER;

fnbuf=strdup(yytext);
len=strlen(fnbuf);
if(fnbuf[len-1]!='\"') {fprintf(stderr,"FATAL:" 
" Unterminated filename\n");exit(1) ;}
if(fnbuf[0]!='\"') {fprintf(stderr,"FATAL:" 
" Unquoted filename\n");exit(1) ;}
fnbuf2=(char *) glb_malloc((len-1)*sizeof(char));
for(i=0;i<len-1;i++) fnbuf2[i]=fnbuf[i+1];
fnbuf2[len-2]='\0';
yyin = glb_fopen( fnbuf2, "r" );

if ( ! yyin ){
fprintf(stderr,"FATAL: Could not open file %s\n",fnbuf2);exit(1);}

file_name_buf[include_stack_ptr]=(char*) strdup(fnbuf2);
glb_file_id=file_name_buf[include_stack_ptr];
line_buf[include_stack_ptr]=glb_line_num;
glb_line_num=0;
glb_free(fnbuf);
glb_free(fnbuf2);

yy_switch_to_buffer(
		    yy_create_buffer( yyin, YY_BUF_SIZE ) );


BEGIN(cond_buf_i);
}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(incl):
case YY_STATE_EOF(grp):
case YY_STATE_EOF(rule):
case YY_STATE_EOF(chl):
case YY_STATE_EOF(energy):
case YY_STATE_EOF(cross):
case YY_STATE_EOF(flux):
case YY_STATE_EOF(defr):
case YY_STATE_EOF(defc):
case YY_STATE_EOF(defe):
case YY_STATE_EOF(defx):
case YY_STATE_EOF(deff):
case YY_STATE_EOF(comment):
case YY_STATE_EOF(str):
#line 160 "glb_lexer.l"
{ if ( --include_stack_ptr < 0 )
{
glb_copy_buff();
glbReset();
/* This lines fixes a tricky bug in the parser */
include_stack_ptr=0;
yyterminate();
}
else
{
yy_delete_buffer( YY_CURRENT_BUFFER );
yy_switch_to_buffer(
		    include_stack[include_stack_ptr] );
glb_line_num=line_buf[include_stack_ptr];
glb_file_id=file_name_buf[include_stack_ptr];
}
}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 179 "glb_lexer.l"
{
yylval.name=yytext;

return GRPOPEN;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 184 "glb_lexer.l"
{
yylval.name=yytext;

return CHANNEL;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 189 "glb_lexer.l"
{yylval.in=+1;return PM;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 190 "glb_lexer.l"
{yylval.in=-1;return PM;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 192 "glb_lexer.l"
{yylval.in=1;return FLAVOR;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 193 "glb_lexer.l"
{yylval.in=2;return FLAVOR;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 194 "glb_lexer.l"
{yylval.in=3;return FLAVOR;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 196 "glb_lexer.l"
{yylval.in=11;return FLAVOR;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 197 "glb_lexer.l"
{yylval.in=12;return FLAVOR;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 198 "glb_lexer.l"
{yylval.in=13;return FLAVOR;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 201 "glb_lexer.l"
{
yylval.name=yytext;

return ENERGY;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 206 "glb_lexer.l"
{
yylval.name=yytext;

return SIGNAL;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 211 "glb_lexer.l"
{
yylval.name=yytext;

return BG;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 218 "glb_lexer.l"
{cond_buf_str=YY_START;BEGIN(str);}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 220 "glb_lexer.l"
{BEGIN(cond_buf_str);}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 222 "glb_lexer.l"
{glb_fatal("Lexer error: Unterminated filename");exit(1);}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 224 "glb_lexer.l"
{
yylval.name=yytext;
return FNAME;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 228 "glb_lexer.l"
{
yylval.name=yytext;
return VERS;
}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 233 "glb_lexer.l"
{
yylval.name=yytext;
return CROSS;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 237 "glb_lexer.l"
{
yylval.name=yytext;
return FLUXP;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 242 "glb_lexer.l"
{
yylval.name=yytext;
return FLUXM;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 247 "glb_lexer.l"
{return RULESEP;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 248 "glb_lexer.l"
{return RULEMULT;} 
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 252 "glb_lexer.l"
{glb_namerec *s;
s = glb_getname (yytext,"rule");
if (s == 0) 
s = glb_putname (yytext,"rule",NAME); 
BEGIN(INITIAL);
BEGIN(rule); 
if(strcmp(s->context,"rule")!=0) 
{yylval.nameptr=s;return RDF;}

yylval.nameptr = s; 

return s->type;
}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 266 "glb_lexer.l"
{glb_namerec *s;
s = glb_getname (yytext,"channel");
if (s == 0) 
s = glb_putname (yytext,"channel",NAME);
BEGIN(INITIAL);
BEGIN(chl); 
if(strcmp(s->context,"channel")!=0) 
{yylval.nameptr=s;return RDF;}
 
yylval.nameptr = s;  

return s->type;
}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 280 "glb_lexer.l"
{glb_namerec *s;
s = glb_getname (yytext,"energy");
if (s == 0) 
s = glb_putname (yytext,"energy",NAME);
BEGIN(INITIAL);
BEGIN(energy);
if(strcmp(s->context,"energy")!=0) 
{yylval.nameptr=s;return RDF;}
 
yylval.nameptr = s; 
 
return s->type;
}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 294 "glb_lexer.l"
{glb_namerec *s;
s = glb_getname (yytext,"cross");
if (s == 0) 
s = glb_putname (yytext,"cross",NAME);
BEGIN(INITIAL);
BEGIN(cross);
if(strcmp(s->context,"cross")!=0) 
{yylval.nameptr=s;return RDF;}
 
yylval.nameptr = s; 
 
return s->type;
}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 309 "glb_lexer.l"
{glb_namerec *s;
s = glb_getname (yytext,"flux");
if (s == 0) 
s = glb_putname (yytext,"flux",NAME);
BEGIN(INITIAL);
BEGIN(flux);
if(strcmp(s->context,"flux")!=0) 
{yylval.nameptr=s;return RDF;}
 
yylval.nameptr = s; 
 
return s->type;
}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 323 "glb_lexer.l"
{glb_namerec *s;
s = glb_getname (yytext,"rule");
if (s == 0) return NDEF;
yylval.nameptr = s; 
return s->type; 
}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 330 "glb_lexer.l"
{
BEGIN(INITIAL);
return GRPCLOSE;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 335 "glb_lexer.l"
{
yylval.name=yytext;
return IDN;
}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 343 "glb_lexer.l"
{yylval.val=atof(yytext); 
return NUM;
}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 347 "glb_lexer.l"
{yylval.name=yytext;return IDN;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 349 "glb_lexer.l"
{
yylval.val=atof(yytext); 
return NUM;
}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 354 "glb_lexer.l"
{
 yylval.val=atof(yytext); 
 return NUM;
}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 359 "glb_lexer.l"
{
yylval.val=atof(yytext); 
return NUM;
}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 364 "glb_lexer.l"
{
yylval.val=atof(yytext); 
return NUM;
}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 369 "glb_lexer.l"
{
yylval.val=atof(yytext); 
return NUM;
}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 377 "glb_lexer.l"
{glb_symrec *s;
s = glb_getsym (yytext);
if (s == 0) 
s = glb_putsym (yytext, VAR); 
yylval.tptr = s; 
return s->type; 
}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 389 "glb_lexer.l"
/* eat up whitespace */
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 391 "glb_lexer.l"
/* empty */
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 393 "glb_lexer.l"
return (int) yytext[0];
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 396 "glb_lexer.l"
/* yylloc.first_line++;*/ glb_line_num++; return '\n';
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 397 "glb_lexer.l"
ECHO;
	YY_BREAK
#line 1390 "glb_lexer.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 246 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 246 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 245);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 397 "glb_lexer.l"




void glb_lexer_cleanup() {
     if( yy_current_buffer != NULL )
     {
         yy_delete_buffer( yy_current_buffer );
         yy_current_buffer = 0;
     }
}


