#line 67 "glb_lexer.l"
#if HAVE_CONFIG_H   /* config.h should come before any other includes */
#  include "config.h"
#endif



#line 9 "glb_lexer.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap(n) 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 67
#define YY_END_OF_BUFFER 68
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[313] =
    {   0,
       63,   63,   16,   16,   63,   63,   63,   63,   63,   63,
       63,   63,   63,   63,   63,   63,   63,   63,   63,   63,
       63,   63,   63,   63,   63,   63,   63,   63,   63,   63,
        4,    4,    0,    0,   35,   35,   68,   65,   63,   66,
       33,   65,   65,   65,   65,   65,   54,   43,   44,   61,
       22,   23,   61,   24,   61,   22,   61,   61,   61,   61,
       17,   16,   67,   18,   52,   44,   20,   21,   44,   44,
       44,   44,   44,   65,   65,   65,   65,   65,   65,    4,
        6,    5,    2,   35,   34,   63,   51,   51,   55,   55,
       55,    0,   62,   57,    3,    1,   56,   54,    0,   61,

       22,   23,   61,   24,   61,   61,   22,   61,   61,   61,
       61,   17,   16,   53,   53,   53,   53,   53,   53,   53,
       53,   45,   45,   46,   46,   47,   47,   48,   48,   49,
       49,   50,   50,    4,    5,    5,    7,   35,   51,   51,
       55,   55,   55,    0,   62,    0,   56,    0,    0,   60,
       61,   61,   61,   22,   61,   61,   61,   61,   53,   53,
       53,   53,   53,   53,   53,   53,   53,   45,   45,   46,
       46,   47,   47,   48,   48,   49,   49,   50,   50,   51,
       55,   55,    0,    0,   59,    0,   58,   61,   61,   61,
       22,   13,   61,   61,    9,   53,   53,   53,   53,   53,

       53,   53,   53,   45,   46,   47,   48,   49,   50,   51,
       55,   55,    0,   61,   61,   12,   61,   61,   61,   53,
       53,   53,   53,   53,   53,   53,   53,   45,   46,   47,
       48,   49,   50,    8,   55,   55,    0,   25,   26,   27,
       61,   11,   61,   14,   53,   53,   53,   53,   53,   53,
       53,   53,   55,   55,    0,   25,   26,   27,   10,   15,
       53,   29,   53,   53,   53,   28,   53,   53,   53,   55,
       36,   64,   53,   53,   53,   19,   53,   53,   53,   37,
       53,   53,   53,   53,   53,   53,   53,   53,   53,   53,
       39,   41,   30,   53,   53,   38,   53,   53,   53,   53,

       40,   42,   53,   53,   53,   53,   53,   53,   53,   31,
       32,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    7,    8,    1,    1,    1,
        1,    9,   10,    1,   11,   12,   13,   14,   14,   14,
       14,   14,   14,   14,   14,   14,   14,   15,    1,   16,
        1,   17,    1,   18,   19,   20,   21,   22,   23,   22,
       24,   22,   22,   22,   22,   25,   26,   27,   28,   22,
       22,   29,   30,   31,   32,   22,   22,   33,   22,   22,
        1,    1,    1,    1,   34,    1,   35,   36,   37,   38,

       39,   40,   41,   42,   43,   22,   44,   45,   46,   47,
       48,   22,   22,   49,   50,   51,   52,   53,   22,   54,
       55,   22,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[56] =
    {   0,
        1,    2,    3,    4,    5,    1,    1,    1,    6,    1,
        1,    1,    1,    7,    1,    1,    1,    1,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    7,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8
    } ;

static yyconst flex_int16_t yy_base[342] =
    {   0,
        0,    0,   54,   56,   23,   27,   61,   65,  105,  145,
      101,  141,  156,  181,  192,  196,  207,  232,   87,  221,
      236,  247,  251,  268,  272,  283,  287,  298,  304,  319,
       62,   66,  636,  635,  632,  631,  635,  640,  632,  640,
      640,  606,   31,  628,  617,   76,   74,  640,  640,    0,
      348,  119,  602,  245,   31,  582,  583,  580,  574,  573,
        0,  622,  640,  640,  640,   56,  640,  640,  586,  583,
      584,  580,  579,  591,  590,  589,  588,  587,  586,    0,
      640,   78,  640,    0,  640,  610,    0,  588,    0,  567,
      570,  584,    0,  114,  640,  640,  163,  177,   85,    0,

        0,  354,  577,  320,  571,  557,  565,  551,  565,  561,
      555,    0,  597,    0,  563,   77,  555,  549,  546,  549,
      548,    0,  569,    0,  568,    0,  567,    0,  566,    0,
      565,    0,  564,    0,   81,   94,  640,    0,    0,  553,
        0,  534,  535,  558,    0,  119,  326,  154,  568,  567,
      559,  532,  528,  528,  522,  530,  529,  534,    0,  535,
      530,  520,  534,  529,  519,  514,  513,    0,  531,    0,
      530,    0,  529,    0,  528,    0,  527,    0,  526,  527,
      522,  506,  507,  540,  539,  538,  514,  484,  466,  460,
      461,    0,  449,  444,    0,  451,  447,  424,  407,  403,

      401,  396,  395,  417,  413,  407,  403,  401,  399,  419,
      369,  376,  398,  377,  378,    0,  360,  375,  358,  370,
      370,  350,  345,  347,  334,  349,  346,  372,  368,  364,
      361,  358,  357,  640,  319,  313,  337,  408,  362,  372,
      312,    0,  315,    0,  301,  303,  129,  307,  287,  299,
      291,  289,  280,  271,  286,    0,  394,  408,    0,    0,
      266,    0,  273,  272,  258,    0,  262,  258,  256,  248,
        0,  640,  240,  248,  227,    0,  223,  220,  218,    0,
      215,  219,  203,  207,  212,  201,  200,  185,  187,  187,
      188,  185,    0,  170,  178,    0,  165,  161,  169,  153,

        0,    0,  150,  144,  140,  131,  127,  123,  113,    0,
        0,  640,  460,  468,  476,  484,  141,  135,  489,  491,
      499,  131,  127,  123,  117,  103,  101,   53,  507,  515,
      523,  525,  527,  529,  531,  533,  535,  537,  539,  541,
      543
    } ;

static yyconst flex_int16_t yy_def[342] =
    {   0,
      312,    1,  313,  313,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
      314,  314,  315,  315,  316,  316,  312,  312,  312,  312,
      312,  317,  318,  319,  312,  312,  312,  312,  312,  320,
      320,  320,  320,  320,  320,   51,  320,  320,  320,  320,
      321,  312,  312,  312,  312,  322,  312,  312,  322,  322,
      322,  322,  322,  323,  324,  325,  326,  327,  328,  329,
      312,  330,  312,  331,  312,  312,  332,  332,  333,  333,
      333,  312,  334,  312,  312,  312,  312,  312,  312,  320,

       51,  320,  320,  320,  320,  320,   51,  320,  320,  320,
      320,  321,  312,  335,  335,  335,  335,  335,  335,  335,
      335,  336,  336,  337,  337,  338,  338,  339,  339,  340,
      340,  341,  341,  329,  330,  330,  312,  331,  332,  332,
      333,  333,  333,  312,  334,  312,  312,  312,  312,  312,
      320,  320,  320,   51,  320,  320,  320,  320,  335,  335,
      335,  335,  335,  335,  335,  335,  335,  336,  336,  337,
      337,  338,  338,  339,  339,  340,  340,  341,  341,  332,
      333,  333,  312,  312,  312,  312,  312,  320,  320,  320,
       51,  320,  320,  320,  320,  335,  335,  335,  335,  335,

      335,  335,  335,  336,  337,  338,  339,  340,  341,  332,
      333,  333,  312,  320,  320,  320,  320,  320,  320,  335,
      335,  335,  335,  335,  335,  335,  335,  336,  337,  338,
      339,  340,  341,  312,  333,  333,  312,  320,  320,  320,
      320,  320,  320,  320,  335,  335,  335,  335,  335,  335,
      335,  335,  333,  333,  312,  238,  320,  320,  320,  320,
      335,  335,  335,  335,  335,  335,  335,  335,  335,  333,
      333,  312,  335,  335,  335,  335,  335,  335,  335,  333,
      335,  335,  335,  335,  335,  335,  335,  335,  335,  335,
      335,  335,  335,  335,  335,  335,  335,  335,  335,  335,

      335,  335,  335,  335,  335,  335,  335,  335,  335,  335,
      335,    0,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312
    } ;

static yyconst flex_int16_t yy_nxt[696] =
    {   0,
       38,   39,   40,   38,   41,   42,   43,   44,   38,   38,
       38,   45,   46,   47,   48,   38,   38,   49,   50,   50,
       50,   50,   51,   50,   50,   52,   53,   50,   50,   50,
       54,   50,   50,   38,   50,   50,   55,   50,   56,   57,
       50,   50,   58,   50,   50,   52,   59,   50,   60,   50,
       54,   50,   50,   50,   50,   62,   63,   62,   63,   50,
      132,   51,   50,   50,   81,   51,   50,   90,   81,   50,
       82,   50,  105,   50,   82,   50,   64,   65,   66,  106,
       64,   65,   66,   91,   95,   97,  136,   98,   96,  312,
      137,  115,   74,  312,  149,  149,   99,   50,  150,   51,

       50,   50,  136,   51,   50,  116,  137,   50,  130,   50,
      128,   50,   99,   50,   67,   68,   64,   65,   70,  161,
       64,   65,   69,   50,  126,   51,   50,   94,  184,  184,
      124,  162,  185,   50,  122,   50,  146,   50,  114,   51,
       50,   50,   89,   51,   50,  102,  102,   50,   87,   50,
      102,   50,  146,   50,   67,   68,   64,   65,   70,  311,
       64,   65,   69,  186,  186,  102,  102,  187,  263,  310,
      102,   64,   65,   71,  309,  264,  147,   50,  308,   51,
       50,   50,  307,   51,   50,  148,  306,   50,   97,   50,
       98,   50,   50,   50,   51,   50,   64,   65,   71,   99,

      305,  148,   50,  304,   50,  303,  302,   64,   65,   72,
      301,   64,   65,   72,  300,   99,  299,   50,  298,   51,
       50,  297,   64,   65,   73,  296,   74,   50,   50,   50,
       51,   50,   50,  295,   51,   50,  294,  293,   50,  292,
       50,   75,   50,   50,   50,   51,   50,   64,   65,   73,
      291,  290,   75,   50,  289,   50,   76,   50,  288,   51,
       50,  287,  286,  104,  285,  284,  283,   50,   50,   50,
       51,   50,   50,   76,   51,   50,  104,   77,   50,  104,
       50,  282,   50,   50,   50,   51,   50,   50,   77,   51,
       50,  281,   78,   50,  280,   50,  104,   50,  279,   50,

      278,  277,  276,   78,   50,  275,   51,   50,   50,   79,
       51,   50,  274,  273,   50,  272,   50,  271,   50,   50,
       50,   51,   50,   50,   79,   51,   50,  270,  269,   50,
      268,   50,  267,   50,   50,   50,   51,   50,  104,  147,
       50,  266,   51,   50,   50,  265,   50,  262,  148,  261,
       50,  104,   50,  260,  104,   50,  259,   51,   50,  255,
      254,  253,  234,  234,  148,   50,  234,   50,  101,  234,
      101,  104,  101,  234,  101,  101,  101,  234,  101,  252,
      102,  102,  251,  250,  101,  102,  101,  249,  257,  257,
      258,  248,  101,  257,  101,  101,  101,  247,  101,  238,

      102,  102,  239,  258,  246,  102,  258,  240,  257,  257,
      245,  244,  243,  257,  242,  238,  241,  237,  236,  235,
      257,  257,  239,  258,  234,  257,  258,  240,  256,  233,
      256,  232,  256,  231,  256,  256,  256,  230,  256,  258,
      257,  257,  258,  229,  256,  257,  256,  228,  227,  226,
      225,  224,  256,  223,  256,  256,  256,  222,  256,  258,
       61,   61,   61,   61,   61,   61,   61,   61,   80,   80,
       80,   80,   80,   80,   80,   80,   63,   63,   63,   63,
       63,   63,   63,   63,   84,   84,   84,   84,   84,   84,
       84,   84,   93,  221,  220,  219,   93,  100,  100,  112,

      218,  217,  112,  112,  112,  112,  112,  134,  134,  216,
      134,  134,  215,  134,  134,  135,  135,  214,  135,  135,
      135,  135,  135,  138,  138,  138,  138,  187,  138,  138,
      138,  139,  139,  141,  141,  145,  145,  159,  159,  168,
      168,  170,  170,  172,  172,  174,  174,  176,  176,  178,
      178,  187,  185,  185,  213,  212,  211,  210,  209,  208,
      207,  206,  205,  204,  203,  202,  201,  200,  199,  198,
      197,  196,  195,  194,  193,  192,  191,  190,  189,  188,
      150,  150,  183,  182,  181,  180,  179,  177,  175,  173,
      171,  169,  167,  166,  165,  164,  163,  160,  113,  158,

      157,  156,  155,  154,  153,  152,  151,  144,  143,  142,
      140,   86,  133,  131,  129,  127,  125,  123,  121,  120,
      119,  118,  117,  113,  111,  110,  109,  108,  107,  103,
       94,   92,   88,   86,  312,   85,   85,   83,   83,   37,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312

    } ;

static yyconst flex_int16_t yy_chk[696] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    3,    3,    4,    4,    5,
      328,    5,    5,    6,   31,    6,    6,   43,   32,    5,
       31,    5,   55,    6,   32,    6,    7,    7,    7,   55,
        8,    8,    8,   43,   46,   47,   82,   47,   46,  135,
       82,   66,   19,  135,   99,   99,   47,    7,   99,    7,

        7,    8,  136,    8,    8,   66,  136,    7,  327,    7,
      326,    8,   47,    8,    9,    9,   11,   11,   11,  116,
        9,    9,    9,   19,  325,   19,   19,   94,  146,  146,
      324,  116,  146,   19,  323,   19,   94,   11,  322,   11,
       11,    9,  318,    9,    9,   52,   52,   11,  317,   11,
       52,    9,   94,    9,   10,   10,   12,   12,   12,  309,
       10,   10,   10,  148,  148,   52,   52,  148,  247,  308,
       52,   13,   13,   13,  307,  247,   97,   12,  306,   12,
       12,   10,  305,   10,   10,   97,  304,   12,   98,   12,
       98,   10,   13,   10,   13,   13,   14,   14,   14,   98,

      303,   97,   13,  300,   13,  299,  298,   15,   15,   15,
      297,   16,   16,   16,  295,   98,  294,   14,  292,   14,
       14,  291,   17,   17,   17,  290,   20,   14,   15,   14,
       15,   15,   16,  289,   16,   16,  288,  287,   15,  286,
       15,   21,   16,   17,   16,   17,   17,   18,   18,   18,
      285,  284,   22,   17,  283,   17,   23,   20,  282,   20,
       20,  281,  279,   54,  278,  277,  275,   20,   18,   20,
       18,   18,   21,   24,   21,   21,   54,   25,   18,   54,
       18,  274,   21,   22,   21,   22,   22,   23,   26,   23,
       23,  273,   27,   22,  270,   22,   54,   23,  269,   23,

      268,  267,  265,   28,   24,  264,   24,   24,   25,   29,
       25,   25,  263,  261,   24,  255,   24,  254,   25,   26,
       25,   26,   26,   27,   30,   27,   27,  253,  252,   26,
      251,   26,  250,   27,   28,   27,   28,   28,  104,  147,
       29,  249,   29,   29,   28,  248,   28,  246,  147,  245,
       29,  104,   29,  243,  104,   30,  241,   30,   30,  237,
      236,  235,  233,  232,  147,   30,  231,   30,   51,  230,
       51,  104,   51,  229,   51,   51,   51,  228,   51,  227,
      102,  102,  226,  225,   51,  102,   51,  224,  239,  239,
      240,  223,   51,  239,   51,   51,   51,  222,   51,  214,

      102,  102,  214,  240,  221,  102,  240,  214,  239,  239,
      220,  219,  218,  239,  217,  214,  215,  213,  212,  211,
      257,  257,  214,  240,  210,  257,  258,  214,  238,  209,
      238,  208,  238,  207,  238,  238,  238,  206,  238,  258,
      257,  257,  258,  205,  238,  257,  238,  204,  203,  202,
      201,  200,  238,  199,  238,  238,  238,  198,  238,  258,
      313,  313,  313,  313,  313,  313,  313,  313,  314,  314,
      314,  314,  314,  314,  314,  314,  315,  315,  315,  315,
      315,  315,  315,  315,  316,  316,  316,  316,  316,  316,
      316,  316,  319,  197,  196,  194,  319,  320,  320,  321,

      193,  191,  321,  321,  321,  321,  321,  329,  329,  190,
      329,  329,  189,  329,  329,  330,  330,  188,  330,  330,
      330,  330,  330,  331,  331,  331,  331,  187,  331,  331,
      331,  332,  332,  333,  333,  334,  334,  335,  335,  336,
      336,  337,  337,  338,  338,  339,  339,  340,  340,  341,
      341,  186,  185,  184,  183,  182,  181,  180,  179,  177,
      175,  173,  171,  169,  167,  166,  165,  164,  163,  162,
      161,  160,  158,  157,  156,  155,  154,  153,  152,  151,
      150,  149,  144,  143,  142,  140,  133,  131,  129,  127,
      125,  123,  121,  120,  119,  118,  117,  115,  113,  111,

      110,  109,  108,  107,  106,  105,  103,   92,   91,   90,
       88,   86,   79,   78,   77,   76,   75,   74,   73,   72,
       71,   70,   69,   62,   60,   59,   58,   57,   56,   53,
       45,   44,   42,   39,   37,   36,   35,   34,   33,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312

    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "glb_lexer.l"
/* GLoBES -- General LOng Baseline Experiment Simulator
 * (C) 2002 - 2007,  The GLoBES Team
 *
 * GLoBES is mainly intended for academic purposes. Proper
 * credit must be given if you use GLoBES or parts of it. Please
 * read the section 'Credit' in the README file.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */
#define YY_NO_UNISTD_H 1
/* This here caused an unpleasant problem:
 * things like
 * %s rule
 * would cause a
 * #define rule xxx
 * statement in glb_lexer.c and that in turn causes
 * trouble with inlcude files which contain
 * glbXXX(int rule)
 * because this will be expanded by the preprocessor to
 * glbXXX(int xxx)
 * which then causes a stupid error of the form
 * parse error before numeric constant
 * The flex manual says that these things have global scope
 * but as usual I read the manual after the fact
 * PH
 */


















#line 73 "glb_lexer.l"
/* need this for the call to atof() below */
#include <math.h>
#include <string.h>

#include "glb_parser_type.h"
#include "glb_parser.h"
#include "glb_error.h"


 #define MAX_INCLUDE_DEPTH 10
static YY_BUFFER_STATE include_stack[MAX_INCLUDE_DEPTH];
static int include_stack_ptr = 0;
int glb_line_num=1;
char *glb_file_id;
static int line_buf[MAX_INCLUDE_DEPTH];
static char *file_name_buf[MAX_INCLUDE_DEPTH];
static int cond_buf;
/* I am not sure wether this works with nested contexts */
static int cond_buf_i;
static int cond_buf_str;
static char *fnbuf,*fnbuf2;
static size_t len,i;

void glb_lexer_cleanup();

// JK, 2010-09-26
// We now allow any character except '"' inside strings to allow for
// multi-line citation information
//FN       [a-zA-Z0-9./][a-zA-Z0-9_./-]*


#line 811 "glb_lexer.c"

#define INITIAL 0
#define glb_lexer_incl 1
#define glb_lexer_grp 2
#define glb_lexer_rule 3
#define glb_lexer_chl 4
#define glb_lexer_energy 5
#define glb_lexer_cross 6
#define glb_lexer_flux 7
#define glb_lexer_nuflux 8
#define glb_lexer_defr 9
#define glb_lexer_defc 10
#define glb_lexer_defe 11
#define glb_lexer_defx 12
#define glb_lexer_deff 13
#define glb_lexer_defnf 14
#define glb_lexer_comment 15
#define glb_lexer_linecomment 16
#define glb_lexer_str 17

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

int yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 116 "glb_lexer.l"


#line 1013 "glb_lexer.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 313 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 640 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 118 "glb_lexer.l"
{cond_buf=YY_START; BEGIN(glb_lexer_linecomment);}
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 119 "glb_lexer.l"
BEGIN(cond_buf);
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 121 "glb_lexer.l"
{cond_buf=YY_START;BEGIN(glb_lexer_comment);}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 122 "glb_lexer.l"
/* eat anything that's not a '*' */
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 123 "glb_lexer.l"
/* eat up '*'s not followed by '/'s */
	YY_BREAK
case 6:
/* rule 6 can match eol */
YY_RULE_SETUP
#line 124 "glb_lexer.l"
++glb_line_num;
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 125 "glb_lexer.l"
BEGIN(cond_buf);
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 127 "glb_lexer.l"
{
glb_copy_buff();
glbReset();
}
	YY_BREAK

case 9:
YY_RULE_SETUP
#line 134 "glb_lexer.l"
{BEGIN(glb_lexer_defr);yylval.name=strdup(yytext);return GID;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 135 "glb_lexer.l"
{BEGIN(glb_lexer_defc);yylval.name=strdup(yytext);return GID;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 136 "glb_lexer.l"
{BEGIN(glb_lexer_defe);yylval.name=strdup(yytext);return GID;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 137 "glb_lexer.l"
{BEGIN(glb_lexer_defx);yylval.name=strdup(yytext);return GID;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 138 "glb_lexer.l"
{BEGIN(glb_lexer_deff);yylval.name=strdup(yytext);return GID;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 139 "glb_lexer.l"
{BEGIN(glb_lexer_defnf);yylval.name=strdup(yytext);return GID;}
	YY_BREAK

case 15:
YY_RULE_SETUP
#line 142 "glb_lexer.l"
{cond_buf_i=YY_START;BEGIN(glb_lexer_incl);}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 144 "glb_lexer.l"
/* eat the whitespace */
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 145 "glb_lexer.l"
{ /* got the include file name */
  if (include_stack_ptr >= MAX_INCLUDE_DEPTH)
  {
    fprintf( stderr, "FATAL: Includes nested too deeply\n" );
    exit( 1 );
  }

// This code rewritten by JK on Mar 30, 2010
//if(include_stack_ptr==0)
//{
//file_name_buf[include_stack_ptr]=glb_file_id;
//line_buf[include_stack_ptr]=glb_line_num;
//}
//
//include_stack[include_stack_ptr++] =
//YY_CURRENT_BUFFER;
//
//fnbuf=strdup(yytext);
//len=strlen(fnbuf);
//if(fnbuf[len-1]!='\"') {fprintf(stderr,"FATAL:"
//" Unterminated filename\n");exit(1) ;}
//if(fnbuf[0]!='\"') {fprintf(stderr,"FATAL:"
//" Unquoted filename\n");exit(1) ;}
//fnbuf2=(char *) glb_malloc((len-1)*sizeof(char));
//for(i=0;i<len-1;i++) fnbuf2[i]=fnbuf[i+1];
//fnbuf2[len-2]='\0';
//yyin = glb_fopen( fnbuf2, "r" );
//
//if ( ! yyin ){
//fprintf(stderr,"FATAL: Could not open file %s\n",fnbuf2);exit(1);}
//
//file_name_buf[include_stack_ptr]=(char*) strdup(fnbuf2);
//glb_file_id=file_name_buf[include_stack_ptr];
//line_buf[include_stack_ptr]=glb_line_num;
//glb_line_num=0;
//glb_free(fnbuf);
//glb_free(fnbuf2);

  /* Remember status of the including file */
  include_stack[include_stack_ptr] = YY_CURRENT_BUFFER;
  file_name_buf[include_stack_ptr] = glb_file_id;
  line_buf[include_stack_ptr]      = glb_line_num;

  /* Remove quotes from filename */
  fnbuf = strdup(yytext);
  len   = strlen(fnbuf);
  if (fnbuf[len-1] != '\"') { fprintf(stderr,"FATAL: Unterminated filename: %s\n", fnbuf); exit(1); }
  if (fnbuf[0] != '\"')     { fprintf(stderr,"FATAL: Unquoted filename: %s\n", fnbuf);     exit(1); }
  glb_file_id = (char *) glb_malloc((len-1)*sizeof(char));
  strncpy(glb_file_id, fnbuf+1, len-2);
  glb_file_id[len-2] = '\0';
  glb_free(fnbuf);

  /* Open included file and re-initialize status variables */
  yyin = glb_fopen(glb_file_id, "r");
  if (!yyin )  { fprintf(stderr,"FATAL: Could not open file %s\n",glb_file_id); exit(1); }
  glb_line_num = 0;
  include_stack_ptr++;
  yy_switch_to_buffer(yy_create_buffer(yyin,YY_BUF_SIZE));
  BEGIN(cond_buf_i);
}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(glb_lexer_incl):
case YY_STATE_EOF(glb_lexer_grp):
case YY_STATE_EOF(glb_lexer_rule):
case YY_STATE_EOF(glb_lexer_chl):
case YY_STATE_EOF(glb_lexer_energy):
case YY_STATE_EOF(glb_lexer_cross):
case YY_STATE_EOF(glb_lexer_flux):
case YY_STATE_EOF(glb_lexer_nuflux):
case YY_STATE_EOF(glb_lexer_defr):
case YY_STATE_EOF(glb_lexer_defc):
case YY_STATE_EOF(glb_lexer_defe):
case YY_STATE_EOF(glb_lexer_defx):
case YY_STATE_EOF(glb_lexer_deff):
case YY_STATE_EOF(glb_lexer_defnf):
case YY_STATE_EOF(glb_lexer_comment):
case YY_STATE_EOF(glb_lexer_linecomment):
case YY_STATE_EOF(glb_lexer_str):
#line 209 "glb_lexer.l"
{
  if (--include_stack_ptr < 0)  /* If top level buffer ends, we're done */
  {
    glb_copy_buff();
    glbReset();
    /* BUGFIX #9 -- This lines fixes a tricky bug in the parser */
    include_stack_ptr = 0;
    yyterminate();
  }
  else                          /* Otherwise, switch back to previous buffer */
  {
    glb_fclose(yyin);
    yy_delete_buffer(YY_CURRENT_BUFFER);
    yy_switch_to_buffer(include_stack[include_stack_ptr]);
    glb_line_num = line_buf[include_stack_ptr];
    glb_free(glb_file_id);
    glb_file_id  = file_name_buf[include_stack_ptr];
  }
}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 230 "glb_lexer.l"
{
yylval.in=-1;
return GRPOPEN;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 234 "glb_lexer.l"
{
yylval.name=strdup(yytext);

return CHANNEL;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 239 "glb_lexer.l"
{yylval.in=+1;return PM;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 240 "glb_lexer.l"
{yylval.in=-1;return PM;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 242 "glb_lexer.l"
{yylval.in=1;return FLAVOR;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 243 "glb_lexer.l"
{yylval.in=2;return FLAVOR;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 244 "glb_lexer.l"
{yylval.in=3;return FLAVOR;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 246 "glb_lexer.l"
{yylval.in=11;return FLAVOR;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 247 "glb_lexer.l"
{yylval.in=12;return FLAVOR;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 248 "glb_lexer.l"
{yylval.in=13;return FLAVOR;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 251 "glb_lexer.l"
{
yylval.name=strdup(yytext);

return ENERGY;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 256 "glb_lexer.l"
{
yylval.name=strdup(yytext);

return SIGNAL;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 261 "glb_lexer.l"
{
yylval.name=strdup(yytext);

return BG;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 266 "glb_lexer.l"
{
yylval.name=strdup(yytext);
return SYS_ON_FUNCTION;
}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 271 "glb_lexer.l"
{
yylval.name=strdup(yytext);
return SYS_OFF_FUNCTION;
}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 278 "glb_lexer.l"
{cond_buf_str=YY_START;BEGIN(glb_lexer_str);}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 280 "glb_lexer.l"
{BEGIN(cond_buf_str);}
	YY_BREAK
/* JK 2010-09-26
    <glb_lexer_str>\n {glb_fatal("Lexer error: Unterminated string");exit(1);}
 */;
case 35:
/* rule 35 can match eol */
YY_RULE_SETUP
#line 286 "glb_lexer.l"
{
yylval.name=strdup(yytext);
return FNAME;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 290 "glb_lexer.l"
{
yylval.name=strdup(yytext);
return VERS;
}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 295 "glb_lexer.l"
{
yylval.name=strdup(yytext);
return VERS;
}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 300 "glb_lexer.l"
{
yylval.name=strdup(yytext);
return CROSS;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 304 "glb_lexer.l"
{
yylval.name=strdup(yytext);
return FLUXP;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 309 "glb_lexer.l"
{
yylval.name=strdup(yytext);
return FLUXM;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 316 "glb_lexer.l"
{
yylval.name=strdup(yytext);
return NUFLUX;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 321 "glb_lexer.l"
{
yylval.name=strdup(yytext);
return NUFLUX;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 326 "glb_lexer.l"
{return RULESEP;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 327 "glb_lexer.l"
{return RULEMULT;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 331 "glb_lexer.l"
{glb_namerec *s;
s = glb_getname (yytext,"rule");
if (s == 0)
s = glb_putname (yytext,"rule",NAME);
BEGIN(INITIAL);
BEGIN(glb_lexer_rule);
if(strcmp(s->context,"rule")!=0)
{yylval.nameptr=s;return RDF;}

yylval.nameptr = s;

return s->type;
}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 345 "glb_lexer.l"
{glb_namerec *s;
s = glb_getname (yytext,"channel");
if (s == 0)
s = glb_putname (yytext,"channel",NAME);
BEGIN(INITIAL);
BEGIN(glb_lexer_chl);
if(strcmp(s->context,"channel")!=0)
{yylval.nameptr=s;return RDF;}

yylval.nameptr = s;

return s->type;
}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 359 "glb_lexer.l"
{glb_namerec *s;
s = glb_getname (yytext,"energy");
if (s == 0)
s = glb_putname (yytext,"energy",NAME);
BEGIN(INITIAL);
BEGIN(glb_lexer_energy);
if(strcmp(s->context,"energy")!=0)
{yylval.nameptr=s;return RDF;}

yylval.nameptr = s;

return s->type;
}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 373 "glb_lexer.l"
{glb_namerec *s;
s = glb_getname (yytext,"cross");
if (s == 0)
s = glb_putname (yytext,"cross",NAME);
BEGIN(INITIAL);
BEGIN(glb_lexer_cross);
if(strcmp(s->context,"cross")!=0)
{yylval.nameptr=s;return RDF;}

yylval.nameptr = s;

return s->type;
}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 388 "glb_lexer.l"
{glb_namerec *s;
s = glb_getname (yytext,"flux");
if (s == 0)
s = glb_putname (yytext,"flux",NAME);
BEGIN(INITIAL);
BEGIN(glb_lexer_flux);
if(strcmp(s->context,"flux")!=0)
{yylval.nameptr=s;return RDF;}

yylval.nameptr = s;

return s->type;
}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 402 "glb_lexer.l"
{glb_namerec *s;
s = glb_getname (yytext,"nuflux");
if (s == 0)
s = glb_putname (yytext,"nuflux",NAME);
BEGIN(INITIAL);
BEGIN(glb_lexer_nuflux);
if(strcmp(s->context,"nuflux")!=0)
{yylval.nameptr=s;return RDF;}

yylval.nameptr = s;

return s->type;
}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 416 "glb_lexer.l"
{glb_namerec *s;
s = glb_getname (yytext,"rule");
if (s == 0) { yylval.name=strdup(yytext); return NDEF; }
yylval.nameptr = s;
return s->type;
}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 423 "glb_lexer.l"
{
BEGIN(INITIAL);
yylval.in=-1;
return GRPCLOSE;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 429 "glb_lexer.l"
{
yylval.name=strdup(yytext);
return IDN;
}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 437 "glb_lexer.l"
{yylval.val=atof(yytext);
return NUM;
}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 441 "glb_lexer.l"
{yylval.name=strdup(yytext);return IDN;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 443 "glb_lexer.l"
{
yylval.val=atof(yytext);
return NUM;
}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 448 "glb_lexer.l"
{
 yylval.val=atof(yytext);
 return NUM;
}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 453 "glb_lexer.l"
{
yylval.val=atof(yytext);
return NUM;
}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 458 "glb_lexer.l"
{
yylval.val=atof(yytext);
return NUM;
}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 463 "glb_lexer.l"
{
yylval.val=atof(yytext);
return NUM;
}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 471 "glb_lexer.l"
{glb_symrec *s;
s = glb_getsym (yytext);
if (s == 0)
s = glb_putsym (yytext, VAR);
yylval.tptr = s;
return s->type;
}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 480 "glb_lexer.l"
{glb_symrec *s;
s = glb_getsym (yytext);
if (s == 0)
s = glb_putsym (yytext, LVAR);
yylval.tptr = s;
return s->type;
}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 492 "glb_lexer.l"
/* eat up whitespace */
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 494 "glb_lexer.l"
/* empty */
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 496 "glb_lexer.l"
return (int) yytext[0];
	YY_BREAK
case 66:
/* rule 66 can match eol */
YY_RULE_SETUP
#line 499 "glb_lexer.l"
/* yylloc.first_line++;*/ glb_line_num++; /*return '\n';*/
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 500 "glb_lexer.l"
ECHO;
	YY_BREAK
#line 1692 "glb_lexer.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 313 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 313 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 312);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 500 "glb_lexer.l"




/* OLD CODE, DOES NOT RUN WITH NEWER FLEX VERSIONS ANYMORE [WW, JK]:

void glb_lexer_cleanup() {
     if( yy_current_buffer != NULL )
     {
         yy_delete_buffer(yy_current_buffer );
         yy_current_buffer = 0;
     }
}
*/



void glb_lexer_cleanup() {
      if( YY_CURRENT_BUFFER != NULL )
          yy_delete_buffer(YY_CURRENT_BUFFER );
}



